name: Build and publish Docker image
on:
  release:
    types: [published]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Build and push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Create tag from repo
        run: | # Uses shell parameter expansion to lowercase
          echo "REPO=${GITHUB_REPO,,}" >>${GITHUB_ENV}

      - name: Build and push image to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            ml_version=2010
          pull: true
          push: true
          tags: ${{ format('ghcr.io/{0}:2010_latest", env.REPO) }}

